site:
    title: Payara Cloud Documentation
    start_page: docs::Overview.adoc
content:
    sources:
    - url: ./
      start_path: docs
      branches: HEAD
asciidoc:
    attributes:
        attribute-missing: 'skip'
        experimental: ''
        page-site-edition: 'qube'  # Set this to test qube locally
ui:
    bundle:
        url: https://github.com/payara/antora-ui-default/releases/download/v2.2/ui-bundle.zip
        snapshot: true
runtime:
    fetch: true
output:
    dir: ./build/html
