site:
  title: Payara Qube Documentation
  start_page: docs::Overview.adoc
  url: https://docs.payara.fish/qube
content:
  sources:
  - url: ./
    start_path: docs
    branches: HEAD
asciidoc:
  attributes:
    attribute-missing: 'skip'
    experimental: ''
    page-site-edition: 'qube'
    source-highlighter: rouge
ui:
  bundle:
    url: https://github.com/payara/antora-ui-default/releases/download/v2.2/ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
  log:
    level: info
output:
  dir: ./build/html
  destinations:
  - provider: fs
    path: ./build/assembler
antora:
  extensions:
  - require: '@antora/pdf-extension'
