// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Pcl Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= pcl-configure(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

pcl-configure - Change configuration of an application

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*pcl configure* [*-eq*] [*--deploy*] [*-a*=_<applicationName>_] [*-n*=_<namespaceName>_]
              [*-o*=_<outputFormat>_] [*-s*=_<subscriptionName>_] [*-t*=_<timeout>_]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Change configuration of an application
Configuration is different for each application. In order to discover which configuration kinds for an application are available, invoke `pcl configuration -n $namespace -a $app configure --help`. 
In order to learn about keys and configuration ids available for specific kind invoke `pcl configuration -n $namespace -a $app configure $kind --help`.
It is possible to chain setting values of multiple configuration kinds in single command.

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-a*, *--application*=_<applicationName>_::
  Name of application to manage. 
+
Not required for commands listed by `-n` option, as well as `list-applications` and `upload`.

*--deploy*::
  Deploy revision with updated configuration immediately

*-e*, *--fail-early*::
  Fail command immediately after first deployment problem instead of waiting for timeout on client or backend side
+
There are certain scenarios when deployment can succeed despite deployment problems reported. 
+
It is therefore not guaranteed that application deployment that failed with early warning will not start up later.

*-n*, *--namespace*=_<namespaceName>_::
  Name of namespace to manage.
+
Required for all commands except `login`, `list-namespaces` and `create-namespace`.

*-o*, *--output*=_<outputFormat>_::
  Output format. Allowed values: TEXT, JSON.

*-q*, *--quiet*::
  Quiet output.
+
Only result of operations will be displayed to `stdout`, or error message to `stderrr`.

*-s*, *--subscription*=_<subscriptionName>_::
  Name of subscription to use. Only necessary when account has access to multiple subscriptions.

*-t*, *--timeout*=_<timeout>_::
  Duration in seconds specifying how long to wait for deployment to complete
+
This is client side timeout which doesn't affect deployment process in Payara Cloud. It is therefore not guaranteed that application deployment that failed due to this time out will not eventually start up later.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
