// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Pcl Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= pcl-start(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

pcl-start - Start an application

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*pcl start* [*-ehlqV*] [*-a*=_<applicationName>_] [*-n*=_<namespaceName>_]
          [*-o*=_<outputFormat>_] [*-s*=_<subscriptionName>_] [*-t*=_<timeout>_]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Start an application
When application is in stopped state it can be started again by means of this command

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-a*, *--application*=_<applicationName>_::
  Name of application to manage. 
+
Not required for commands listed by `-n` option, as well as `list-applications` and `upload`.

*-e*, *--fail-early*::
  Fail command immediately after first deployment problem instead of waiting for timeout on client or backend side
+
There are certain scenarios when deployment can succeed despite reported deployment problems.
+
This means that even if you receive early warning messages about deployment failures, the application might still start up and run properly later.

*-h*, *--help*::
  Show this help message and exit.

*-l*, *--logs*::
  Show application's logs during deployment

*-n*, *--namespace*=_<namespaceName>_::
  Name of namespace to manage.
+
Required for all commands except `login`, `list-namespaces` and `create-namespace`.

*-o*, *--output*=_<outputFormat>_::
  Output format. Allowed values: TEXT, JSON.

*-q*, *--quiet*::
  Quiet output.
+
Only result of operations will be displayed to `stdout`, or error message to `stderrr`.

*-s*, *--subscription*=_<subscriptionName>_::
  Name of subscription to use. Only necessary when account has access to multiple subscriptions.

*-t*, *--timeout*=_<timeout>_::
  Duration in seconds specifying how long to wait for deployment to complete
+
This is client side timeout which doesn't affect deployment process in Payara Cloud. It is therefore not guaranteed that application deployment that failed due to this time out will not eventually start up later.

*-V*, *--version*::
  Print version information and exit.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
