// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Qube Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= qube-upload(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

qube-upload - Upload an application binary (.war file) to Payara Qube (Managed).

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*qube upload* [*-ehlqV*] [*--deploy*] [*-a*=_<applicationName>_] [*--endpoint*=_<baseUri>_]
            [*-n*=_<namespaceName>_] [*-o*=_<outputFormat>_] [*-s*=_<subscriptionName>_]
            [*-t*=_<seconds>_] _<file>_

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Upload an application binary (.war file) to Payara Qube (Managed).
This command can either provide a new binary for an existing application or upload a new application into a namespace.

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-a*, *--application*=_<applicationName>_::
  Name of application to manage. 
+
Not required for commands listed by `-n` option, as well as `list-applications` and `upload`.

*--deploy*::
  Deploy the application immediately after uploading.
+
The application will only deploy if its default configuration is complete  (i.e., all required options have default values).

*-e*, *--fail-early*::
  Fail command immediately after first deployment problem instead of waiting for timeout on client or backend side
+
There are certain scenarios when deployment can succeed despite reported deployment problems.
+
This means that even if you receive early warning messages about deployment failures, the application might still start up and run properly later.

*--endpoint*=_<baseUri>_::
  Management endpoint. Defaults to https://manage.payara.cloud. Set it to the management endpoint for your Payara Qube environment if you use a custom domain. Also settable with environment variable QUBE_ENDPOINT

*-h*, *--help*::
  Show this help message and exit.

*-l*, *--logs*::
  Shows application deployment logs in real-time

*-n*, *--namespace*=_<namespaceName>_::
  Name of namespace to manage.
+
Required for all commands except `login`, `list-namespaces` and `create-namespace`.

*-o*, *--output*=_<outputFormat>_::
  Set the output format. Allowed values: TEXT, JSON.

*-q*, *--quiet*::
  Enable quiet output.
+
Only result of operations will be displayed to `stdout`, or error message to `stderrr`.

*-s*, *--subscription*=_<subscriptionName>_::
  Specify the name of the subscription to use. This is only necessary when your account has access to multiple subscriptions.

*-t*, *--timeout*=_<seconds>_::
  Sets how long to wait for deployment completion on the client side.
+
This timeout doesn't affect the actual deployment process in Payara Qube (Managed), so applications might still start up even after a timeout occurs.

*-V*, *--version*::
  Print version information and exit.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
== Arguments

_<file>_::
  Application archive file (.war) to be uploaded

// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
