// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: qube version  development-snapshot
:manmanual: Qube Manual
:mansource: qube version  development-snapshot
:man-linkstyle: pass:[blue R < >]
= qube(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

qube - Payara Qube Command Line.

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*qube* [*-hqV*] [*-a*=_<applicationName>_] [*--endpoint*=_<baseUri>_] [*-n*=_<namespaceName>_]
     [*-o*=_<outputFormat>_] [*-s*=_<subscriptionName>_] [COMMAND]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Payara Qube Command Line Interface allows remote operations over Payara Qube's namespaces and application via command line.
In order to sign in, use the command `qube login` interactively. This will allow the client to obtain credentials that are either stored in home directory or can be provided via environment variable `QUBE_AUTH_TOKEN`. See `qube login --help` for details.

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-a*, *--application*=_<applicationName>_::
  Name of application to manage. 
+
Not required for commands listed by `-n` option, as well as `list-applications` and `upload`.

*--endpoint*=_<baseUri>_::
  Management endpoint. Defaults to https://manage.payara.cloud. Set it to management endpoint of your Payara Qube instance if that’s your target. Also settable with environment variable QUBE_ENDPOINT

*-h*, *--help*::
  Show this help message and exit.

*-n*, *--namespace*=_<namespaceName>_::
  Name of namespace to manage.
+
Required for all commands except `login`, `list-namespaces` and `create-namespace`.

*-o*, *--output*=_<outputFormat>_::
  Set the output format. Allowed values: TEXT, JSON.

*-q*, *--quiet*::
  Enable quiet output.
+
Only result of operations will be displayed to `stdout`, or error message to `stderr`.

*-s*, *--subscription*=_<subscriptionName>_::
  Specify the name of the subscription to use. This is only necessary when your account has access to multiple subscriptions.

*-V*, *--version*::
  Print version information and exit.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
== Commands

xref:qube-login.adoc[*login*]::
  Log in to Payara Qube instance.

xref:qube-list-subscriptions.adoc[*list-subscriptions*]::
  Get list of subscriptions available to user.

xref:qube-list-namespaces.adoc[*list-namespaces*]::
  List namespaces available in a subscription.

xref:qube-list-applications.adoc[*list-applications*]::
  List applications present in a namespace.

xref:qube-upload.adoc[*upload*]::
  Upload an application binary (.war file) to Payara Qube.

xref:qube-deploy.adoc[*deploy*]::
  Deploy an existing application.

xref:qube-start.adoc[*start*]::
  Start an application

xref:qube-stop.adoc[*stop*]::
  Stop an application

xref:qube-create-namespace.adoc[*create-namespace*]::
  Create new namespace

xref:qube-delete-namespace.adoc[*delete-namespace*]::
  Deletes a namespace.

xref:qube-delete-application.adoc[*delete-application*]::
  Delete an application.

xref:qube-configure.adoc[*configure*]::
  Change configuration of an application

xref:qube-scale.adoc[*scale*]::
  Scale an application

// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
