= Pricing

Payara Cloud is billed only by single usage metric -- virtual CPU cores reserved for your application to make it run.
The metric is captured every minute and summarize at the end of the billing cycle, which is 30 days.

The minimum reservation for an application is one quarter of a core and the largest currently supported reservation for a single application is 4 cores.

Cost for a vCPU core starts at *$0.005* per minute and goes down as you reserve more cores.

The offer is separated into three different plans based on your needs:

* **Pay As You Go**: You can scale down your usage to 0, but cannot exceed a usage quota of 2 vCPU cores at any time.
* **Standard**: You pay in advance for 2 vCPU cores (60 vCPU days) but can scale up to 32 vCPU cores and enjoy a lower price per core.
* **Premium**: Starts at 16 vCPU cores and includes access to Payara's Service Team to help you solve any problems you might have with your application.

== Features And Limits of Plans

|===
| Plan | Pay As You Go | Standard | Premium

h| Usage Quota
| 0--2 vCPU cores
| 2--32 vCPU cores
| 16--64 vCPU cores

h| Custom domains
| yes
| yes
| yes

h| Log Retention
| 30 days
| 30 days
| 30 days

h| Exports and Dumps retention
| 7 days
| 7 days
| 7 days

h| Horizontal scaling
| no
| yes
| yes


h| 10x5 Support
| no
| no
| yes
|===

== Price per vCPU minute

|===
| Plan | Pay As You Go | Standard | Premium

h| Fixed fee
| $0
| $432
| $3300

h| 0--60 +
vCPU days
| $0.005
| $0.005 +
(included in fixed fee)
.4+| $0.00477 +
(included in fixed fee)

h| 60--120 +
vCPU days
.4+| --
| $0.00463

h| 120--240 +
vCPU days
| $0.00445

h| 240--480 +
vCPU days
| $0.00429

h| more than 480 +
vCPU days
| $0.00413
| $0.00442
|===

== Pricing Examples

Here are some examples of continuous usage costs for different types of applications.
Take note, that usage is calculated per minute and continuous use is not the only use case for Payara Cloud.

=== Minimum continuous usage

The smallest application you can deploy on Payara cloud would have reservation of 0.25 vCPU core. The cost of running such application for a month would be:

> $0.005 * 0.25 * 60 * 24 * 30 = $54

The price can further go down once you'd automate your deployment and invoke kbd:[Start] and kbd:[Stop] commands on your application only for times when you need it.

=== Single production application

We recommend reserving at least 2 vCPU cores for a production application.

The cost of running such application for a month would be:

> $0.005 * 2 * 60 * 24 * 30 = $432

=== Large application

Assume a horizontally scaled application with 2 x 2 vCPU cores accompanied by a third application for which half a core reservation suffices.

Here the different usage bands come into play

> First 2 cores over 30 days: $0.005 * 2 * 60 * 24 * 30 = $432
>
> Next 2 cores over 30 days: $0.00477 * 2 * 60 * 24 * 30 = $400
>
> Next Half a core over 30 days : $0.00445 * 0.5 * 60 * 24 * 30 = $96,12
>
> Total: $432 + $400 + $96,12 = $928,12




