[[overview]]
= Documentation Overview

This page provides some general information about the Payara Platform Community Edition.

[[issue-tracking]]
=== Issue Tracking

We make use of GitHub's integrated https://github.com/payara/Payara/issues[issue tracker]
to allow the community to create enhancement and bug fix requests.
The only requirements to create a bug fix or enhancement request is a
GitHub account, and a reproducible bug or idea for an enhancement; you do
not need to sign the _CLA_ to create an enhancement or bug fix request.
We also provide an https://github.com/payara/Payara/blob/master/.github/ISSUE_TEMPLATE.md[Issue Template]
that can help you describe bug reports or enhancement requests in an
easier manner.

Someone on the Payara team, or someone from the community, will then
investigate and converse with you about the enhancement request or bug report.

We also attach labels and milestones to issues to help both us, and the
community, manage the workflow of these issues.

[[documentation]]
== Documentation

We make use of Antora to store and host our technical documentation about
Payara, as well as general information (such as this document) about the
Payara project.

For technical documentation, we only store documentation that we have
written, which typically pertains to new or modified features and commands
made by us or the community; we do not host GlassFish documentation,
nor will we rewrite it for unmodified modules.
